# Generated by Django 5.1.2 on 2024-11-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_user_timezone_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='multi_factor_auth_enabled',
            field=models.BooleanField(default=False, verbose_name='multi-factor authentication enabled'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('account_deletion', 'Account Deletion')], max_length=20),
        ),
    ]
