# Generated by Django 5.1.2 on 2024-11-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_multi_factor_auth_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('account_deletion', 'Account Deletion'), ('disable_email_2fa', 'Disable Email 2FA')], max_length=20),
        ),
    ]
