# Generated by Django 5.1.2 on 2024-11-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_emailverification_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('account_deletion', 'Account Deletion'), ('disable_email_2fa', 'Disable Email 2FA'), ('password_change', 'Password Change')], max_length=20),
        ),
    ]
