# fly.toml app configuration file generated for splashcat on 2023-06-12T20:53:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "splashcat"
primary_region = "iad"
console_command = "/code/manage.py shell"

[deploy]
release_command = "python manage.py migrate"
strategy = "canary"

[env]
PORT = "8000"
DJANGO_ALLOWED_HOSTS = "splashcat.fly.dev,splashcat.ink"
DEBUG = "False"
SENTRY_DSN = "https://9babb5ac79274bed8e3c56a222b44ab6@o4505055559352320.ingest.sentry.io/4505055561449472"

[[services]]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[[services.http_checks]]
interval = "10s"
grace_period = "5s"
method = "get"
path = "/"
protocol = "http"
restart_limit = 5
timeout = "5s"
tls_skip_verify = false
[services.http_checks.headers]

[[statics]]
guest_path = "/code/staticfiles"
url_prefix = "/static/"

[processes]
app = "daphne -b 0.0.0.0 splashcat.asgi:application"
celery-worker = "celery -A splashcat worker -l INFO -B"
