[tool.poetry]
name = "splashcat"
version = "0.1.0"
description = ""
authors = ["kitt <catgirl@catgirlin.space>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.2"
django-htmx = "^1.14"
django-allauth = "^0.54"
django-debug-toolbar = "^4.0"
djangorestframework = "^3.14"
channels = "^4.0"
daphne = "^4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
